### ISSUE TITLE
Compile error in test class

### ISSUE THREAD

**Issue by buergerj** [avicomp/ont-api#13]
When I try to build ONT-API by importing it in Eclipse, I get a AxiomsRoundTrippingTestCase
```
    @Parameters
    public static List<AxiomBuilder> getData() {
        return Arrays.asList(
                // SWRLRuleAlternateNS
                () -> {
                    Set<OWLAxiom> axioms = new HashSet<>();
```
Error: Type mismatch: cannot convert from List<Object> to List<TestBase.AxiomBuilder>	AxiomsRoundTrippingTestCase.java	/ontapi/src/test/java/org/semanticweb/owlapi/api/test/baseclasses	line 106	Java Problem

**Comment by sszuev** [comment]
looks like eclipse bug, not ont-api.
anyway some cosmetic changes can be made to this test. since even in idea there is warning about slowdown with large varangs.
just note, this is copy-pasted class from owlapi-contract https://github.com/owlcs/owlapi/blob/version5/contract/src/test/java/org/semanticweb/owlapi/api/test/baseclasses/AxiomsRoundTrippingTestCase.java
